### ISSUE TITLE
订阅定制配置

### ISSUE THREAD

**Issue by FightKK7** [Crazy-MT/feishu-gemini#1]
请问下这个订阅地址如何配置？
![screenshot-20231219-120846](https://github.com/Crazy-MT/feishu-gemini/assets/44563734/342f0c17-ea37-44fd-b7a8-d1bc73c2cd0a)

**Comment by Crazy-MT** [comment]
我是用内网穿透的服务。
python 运行在本地，内网穿透服务提供外网访问地址的。
可以用 cpolar 做内网穿透，很方便。
