### ISSUE TITLE
飞书发送消息，服务端报错KeyError: 'header'

### ISSUE THREAD

**Issue by MrSSai** [Crazy-MT/feishu-gemini#2]
飞书机器人已经开通了，权限开通了。
在飞书机器人发送消息时，服务端报错。请问可能是什么原因
![image](https://github.com/Crazy-MT/feishu-gemini/assets/29100889/e27468a4-48a6-4ac5-a5c3-dbc461c7ff0d)

**Comment by Crazy-MT** [comment]
飞书发送来的消息没有 header 字段？ 
![1](https://github.com/Crazy-MT/feishu-gemini/assets/12363566/1dc22538-b08c-4577-8ebf-aef203a8ae84)
是开通的这俩接口不？
